version: '3.1'

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_DB: database

    ports:
      - "5432:5432"
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/create_tables.sql
